#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Masato Hasegawa
# SPDX-License-Identifier: BSD-3-Clause
import sys

def tonum(s):
    try:
        return int(s)
    except:
        return float(s)

x = 0
for line in sys.stdin:
    x += tonum(line)

print(x)
