#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Masato Hasegawa
# SPDX-License-Identifier: BSD-3-Clause
import sys

x = 0
for line in sys.stdin:
    try:
        x += int(line)
    except:
        x += float(line)
print(x)
